pipeline {
    agent none
stages{
    stage (build){
    agent {
     docker {
        image 'python:2.7.16-slim' 
        args '-v $HOME/.m2:/root/.m2'
        args '--user root'
    }
    }
    
    steps{

      echo 'Compiling Vote app'
      dir ('vote'){
           sh 'pip install -r requirements.txt'
        }
        
    }
 }
   # stage (Test){
  #  agent {
    # docker {
       # image 'python:2.7.16-slim' 
      #  args '-v $HOME/.m2:/root/.m2'
     #   args '--user root'
   # }
   # }
   #  steps{

   #   echo 'Test Vote app'
      dir('vote'){
         sh 'nosetests -v'
                
      #  }
        
  #  }
#}
stage ('docker-Package') {
        agent any
    steps{
        echo 'Running unit test on vote App'
        script{
            docker.withRegistry('https://index.docker.io/v1/', 'test') {

            def voteImage = docker.build("aderock/vote:v1", "./vote")
            voteImage.push()
            voteImage.push("${env.BRANCH_NAME}")
                    
                

                }
                
            }
        }
    }
}
}