pipeline {
    agent {
     docker {
        image 'python:slim-buster' 
        args '-v $HOME/.m2:/root/.m2'
    }
    }
stages{
    stage (build){
    
    steps{

      echo 'Compiling Vote app'
      dir ('vote'){
           sh 'pip install -r requirements.txt'
        }
        
    }
 }


    stage (Test){
  
    steps{

      echo 'Test Vote app'
      dir('vote'){
                  sh 'nosetests -v '
                
                }
        
    }
}
}
}