pipeline {
    agent {
     docker {
        image 'maven:amazoncorretto' 
        args '-v $HOME/.m2:/root/.m2'
    }
    }
    stages{
        stage ('build') {
         
            steps{
              echo 'Compliling worker app'
              dir ('worker'){
               sh 'mvn compile'
              }
            }
                
        }
        
        stage ('test') {
           
            steps{
                echo 'Running unit test on worker App'
                
            }
        }
        stage ('package') {
            
            steps{
                echo 'Packaging worker App'
                dir('worker'){
            sh 'mvn package -Dskiptest'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
             }
            }

          stage ('docker-Package') {
           
            steps{
                echo 'Running unit test on worker App'
                script{
                  docker.withRegistry('https://index.docker.io/v1/', 'dockerlogin') {

                def workerImaage = docker.build("aderock/worker:${env.BUILD_ID}", "./worker")

                workerImage.push()
                workerImage.push("${env.BRANCH_NAME}")
                

                }
                
            }
        }
    }
    post{
     always{
         echo 'Build pipeline for workers is complete..'
     }
   }


}
}
