pipeline {
    agent {
     docker {
        image 'Maven:amazoncorretto' 
        args '-v $HOME/.m2:/root/.m2'
    }
    }
    stages{
        stage ('build') {
             when{
                changeset "**/worker/**"
            }
            steps{
              echo 'Compliling worker app'
              dir ('worker'){
               sh 'mvn compile'
              }
            }
                
        }
        
        stage ('test') {
             when{
                changeset "**/worker/**"
            }
            steps{
                echo 'Running unit test on worker App'
                
            }
        }
        stage ('package') {
            when{
                branch 'master'
                changeset "**/worker/**"
            }
            steps{
                echo 'Packaging worker App'
                dir('worker'){
            sh 'mvn package -Dskiptest'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
             }
            }
        }
    }
    post{
     always{
         echo 'Build pipeline for workers is complete..'
     }
   }

}
