pipeline {
    agent none 
    stages{
        stage ('build') {
        agent {
          docker {
        image 'maven:amazoncorretto' 
        args '-v $HOME/.m2:/root/.m2'
       }
        }
            steps{
              echo 'Compliling worker app'
              dir ('worker'){
               sh 'mvn compile'
              }
            }
                
        }
        
        stage ('test') {
            agent {
     
          docker {
        image 'maven:amazoncorretto' 
        args '-v $HOME/.m2:/root/.m2'

        }
            }
           
            steps{
                echo 'Running unit test on worker App'
            
            }
        }

        stage ('package') {
            agent {
     docker {
        image 'maven:amazoncorretto' 
        args '-v $HOME/.m2:/root/.m2'
    }
            }

            steps{
                echo 'Packaging worker App'
                dir('worker'){
            sh 'mvn package -Dskiptest'
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
             }
            }
        }

          stage ('docker-Package') {
              agent any
            steps{
                echo 'Running unit test on worker App'
                script{
                  docker.withRegistry('https://index.docker.io/v1', 'test') {

                   def workerImage = docker.build("aderock/worker:v1", "./worker")
                    workerImage.push()
                    workerImage.push("${env.BRANCH_NAME}")
                    
                

                }
                
            }
        }
    }
    
}
}